### ISSUE TITLE
Not able to download REPO

### ISSUE THREAD

**Issue by pranavaryans1987** [halogenOS/android_manifest#12]
repo init -u https://github.com/halogenOS/android_manifest.git -b XOS-7.1

can't download repo, please suggest something..

**Comment by xdevs23** [comment]
Please show us the error you are getting otherwise we are not able to help you. It's worth noting that XOS 7 has been end of life for a long while now.
Reopen this issue if you can provide the error.

**Comment by msfjarvis** [comment]
7.1 is deprecated and no support will be offered anymore. If you cannot debug and correct a manifest yourself, don't attempt building ROMs just yet.
