### ISSUE TITLE
error: Cannot fetch android_hardware_qcom_display

### ISSUE THREAD

**Issue by SavinoSchiavone** [halogenOS/android_manifest#6]
I get this error when it arrives at 99%

This is the final log:

Fetching projects:  99% (520/525)  fatal: Not a git repository: '/home/michele/Documenti/Android ROM/.repo/projects/hardware/qcom/display-caf/msm8952.git'
error: Cannot fetch android_hardware_qcom_display
warn: --force-broken, continuing to sync
Fetching project android_hardware_qcom_display
Fetching project android_hardware_qcom_display
Fetching project android_hardware_qcom_display
Fetching project android_hardware_qcom_display
Fetching projects: 100% (525/525)  
error: Exited sync due to fetch errors

How can I resolve it?

**Comment by msfjarvis** [comment]
`rm -rf` the directory in question and resync

**Comment by xdevs23** [comment]
@SavinoSchiavone Lol

**Comment by SavinoSchiavone** [comment]
@xdevs23 what? I'm with this things, I need help :c
