### ISSUE TITLE
Another final error

### ISSUE THREAD

**Issue by SavinoSchiavone** [halogenOS/android_manifest#7]
Now I get this at the end

From https://github.com/halogenOS/android_hardware_qcom_display
 * [new branch]    cm-14.1-caf-8996 -> XOS/cm-14.1-caf-8996
Fetching projects: 100% (525/525)  
error: Exited sync due to fetch errors

**Comment by xdevs23** [comment]
Do you even know how to Android?

**Comment by SavinoSchiavone** [comment]
@xdevs23 No, I don't know I to use it. If I know I don't ask.... Thanks a lot for the help ;)
